### ISSUE TITLE
joint fit example with TOI-141 not converging

### ISSUE THREAD

**Issue by jkteske** [nespinoza/juliet#23] opened 2020-05-27 23:33 UTC
I'm following the example of a joint fit (https://juliet.readthedocs.io/en/latest/tutorials/jointfits.html) but the fit is not converging. I keep getting this message after about 2 hours:

MultiNest Warning!
 Parameter            4  of mode            1  is converging towards the edge of the prior.

The tutorial says it takes about an hour to run on a laptop (which is what I'm using), but this seems stuck. Any suggestions? Thanks!

**Comment by nespinoza** [comment] 2020-05-28 13:04
Hi Johanna,

 Thanks for the feedback on this! Does the message gets updated, or you don't get any more outputs from the code? There are two options here, and would like to check which one might be it. Have you tried running it again?

Néstor

**Comment by jkteske** [comment] 2020-05-28 13:15
Yes, I tried running it again and had the same issue. It's hard to tell if the message is getting updated or not, since it's the same message (after a while my terminal window does not appear to change, just shows the same message printed over and over). I think it is getting updated, but I'm not 100% sure.

**Comment by nespinoza** [comment] 2020-05-28 13:26
Well, it could be several things:

1. Each run is different, so it might take a little more or less time on each run.
2. Our laptops can be different, and therefore, while it took me an hour in mine it might take you a little more in yours (although _several hours_ smells like a problem to me).
3. There are some known portions of the parameter space where `batman` gets hang up, and it might be that the fit is trying to explore those regions and thus getting stuck (I'm currently having this problem with a system, and plan to be fixing that in the next few days (by implementing `starry` into `juliet`), but for now there is no way around it other than, e.g., constraining the range of plant-to-star radius ratios to more sensible ranges via `pu` and `pl`). There is no way to know if this is the case in your runs right now because there is no random state defined at the beginning of the runs I presume. Could you try running another run on this dataset and setting `np.random.seed(X)` where `X` is any number you want? With that I can try to reproduce the exact same run on my laptop to see what is going on.

**Comment by jkteske** [comment] 2020-05-28 13:44
Okay, thanks. I just started again with np.random.seed(22).

**Comment by nespinoza** [comment] 2020-05-28 14:01
Hi @jkteske --- I think I just found the problem! The fit is never going to converge, because the times in the TESS timestamps are in modified TESS JD, whereas the RVs are in JD. Very dumb of me of not including this conversion in the docs (but, of course, in the script I have in my computer they are OK). I'll fix that now in the docs.

Sorry about this! 

Néstor

**Comment by nespinoza** [comment] 2020-05-28 14:48
Hi @jkteske --- I've updated the documentation with the correct time conversions in https://github.com/nespinoza/juliet/commit/0d1c1133222e8b05fbb80e4316802a8dbfc23d1d (which has updated the docs: https://juliet.readthedocs.io/en/latest/tutorials/jointfits.html). I've just checked copy-pasting that in my computer, and it took 1.3 hours to finish (~1 hour and 20 mins).

Let me know if this fixed this issue, so I can close this!

Best,
Néstor

**Comment by jkteske** [comment] 2020-05-29 01:50
It's now been about 4 hours, and the following message keeps coming up (is definitely updating, but very slowly):

MultiNest Warning!
 Parameter            4  of mode            1  is converging towards the edge of the prior.
 Parameter           21  of mode            1  is converging towards the edge of the prior.

**Comment by nespinoza** [comment] 2020-05-29 01:52
Have you updated the fit with the changes I made above in the docs?

**Comment by jkteske** [comment] 2020-05-29 01:54
Yes, I modified it to replace the old version with:

# Put data in dictionaries, add 2457000 to the times to convert from TESS JD to JD:
times, fluxes, fluxes_error = {},{},{}
times['TESS'], fluxes['TESS'], fluxes_error['TESS'] = t + 2457000,f,ferr

**Comment by nespinoza** [comment] 2020-05-29 02:03
Yes, that's also important! Let me know how it goes in about an hour. Hope that solved it.

**Comment by nespinoza** [comment] 2020-05-29 16:57
Yay! I'll go ahead and close this issue then. If there are any other issues, please, let us know by opening another Github issue!

N.

**Closed by nespinoza** 2020-05-29 16:57 UTC
Labels: bug, documentation
